### ISSUE TITLE
Blank page after deployment

### ISSUE THREAD

**Issue by perezdf** [dukescript/dukescript-twitter#1]
I am using the android module in a smartphone Collo DG100. Build looks ok, however, when I start up the application, a blank page appers. Any suggestion about how to dig in the issue?

**Comment by dukescript** [comment]
Best way to start is to run the General Client Code Project and see what is printed on the console. If it works there you can run it on Android and add this on the console:

adb logcat

If you see any info that seems related you can dig deeper. 

But before you do any of that:

Did you get and add your bearer token from Twitter? 

—Toni

Am 29.05.2015 um 17:17 schrieb perezdf notifications@github.com:

**Comment by dukescript** [comment]
Closing, worksforme and no feedback from original reporter.
